// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWYEZ6UUSUZwPVwrxVhljLnK6cr1-CtnU',
    appId: '1:785423143467:web:6f009f9dc60ae7e3dd506e',
    messagingSenderId: '785423143467',
    projectId: 'cancer-project-df94e',
    authDomain: 'cancer-project-df94e.firebaseapp.com',
    storageBucket: 'cancer-project-df94e.appspot.com',
    measurementId: 'G-S6P8X1Y55F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTL1NpGfzGR4hmduf9mGMvppSYmWiFmI',
    appId: '1:785423143467:android:fd4cd6261185f959dd506e',
    messagingSenderId: '785423143467',
    projectId: 'cancer-project-df94e',
    storageBucket: 'cancer-project-df94e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATXr0DPLVEaxOoMFXAmlVs-m1fkHBbJdc',
    appId: '1:785423143467:ios:c413912cd336a6cadd506e',
    messagingSenderId: '785423143467',
    projectId: 'cancer-project-df94e',
    storageBucket: 'cancer-project-df94e.appspot.com',
    iosBundleId: 'com.example.cancerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATXr0DPLVEaxOoMFXAmlVs-m1fkHBbJdc',
    appId: '1:785423143467:ios:93de3ca7bc3d249cdd506e',
    messagingSenderId: '785423143467',
    projectId: 'cancer-project-df94e',
    storageBucket: 'cancer-project-df94e.appspot.com',
    iosBundleId: 'com.example.cancerProject.RunnerTests',
  );
}
